### PR TITLE
Fixes for video and image view now (Issue #2421)

### LINKED ISSUE #2421: No recording "view now" option in browser with 0.43
I recently updated to 0.43 / Python3 and there is no longer an option to watch a recording directly in the browser, there is only an option to download the recording. Is that intentional?

### PR DESCRIPTION
**Pull request by tunkio**
Fix #2421 and broken image view now

### CODE REVIEW

**Comment by MichaIng** [comment]
While `.click()` still works, it is deprecated as well and should be replaced the same way: https://github.com/jquery/jquery-migrate/blob/main/warnings.md#shorthand-deprecated-v3-jqmigrate-jqueryfnclick-event-shorthand-is-deprecated

**Comment by MichaIng** [comment]
Updated all other cases of `.load()`, `.click()` and `.error()` among all JavaScript files, including the CSS browser selector. That one I guess we could drop, given that all relevant browser versions support likely all relevant modern CSS and JavaScript features. However, to be done in a dedicated PR.

**Comment by tunkio** [comment]
Nice! Didn't even think about those other ones.

**Comment by MichaIng** [comment]
Reason and changes are well documented in jQuery docs and of trivial kind. However, at least we should do one round trip through the web interface to assure we did not accidentally introduce a syntax error or typo not caught by CI 😉.

**Review by zagrim — APPROVED** [review]
Looks good to me.

**Review by MichaIng — APPROVED** [review]
Works well here. Let's merge this.

**Pull request merged**
