### PR TITLE
Review overall changes done to dev

### PR DESCRIPTION
**Pull request by MichaIng**
This is ONLY to get an overview of all changes done to `dev`, since it happened quite fast.

### CODE REVIEW

**Comment by MichaIng** [comment]
@jmichault 
To better understand the refactoring you did:
- You split `handlers.py` and `utils.py` into separate scripts in respective sub directories? Fine from my end.
- You moved `extra/` into `motioneye/`. What is the reason behind this? Generally I think it's fine to leave only code to run motionEye in  `motioneye/` and leave all Docker, service and example configs in the parent directory.

Regarding internationalisation, I'd vote for using English language as primary language, which makes it much easier for contributors to understand the texts and add/fix languages without the need to learn Esperanto first. Not sure how big the effort would be to change this, i.e. if this can be somehow automated without copy&pasting all strings manually back and forth.

**Comment by jmichault** [comment]
@MichaIng 
I moved `extra/` because it's the easiest way I've found to include files in the pip package that are ultimately going to go in `/etc/`. Thus allowing a simpler installation with pip:
* `sudo pip install motioneye` installs motioneye
* `sudo motioneye_init` install motion and other useful packages, create motioneye service, create various folders ...

**Comment by MichaIng** [comment]
Okay, understood, generally nice to ship a little installer with the Python module itself. Then let's move everything Docker and other non-required files (logos/images as well) back into parent/extra. About `sudo motioneye_init` I think you need to check out talk in the other thread, as it is now working currently 🙂.

**Comment by MichaIng** [comment]
@jmichault 
Current `pip install motioneye` ships those extra files in `/usr/local/share/motioneye` (when installed as global module) which I actually like. What do you think about keeping this as it was, so users which possibly have their install scripts do not need to change it? The other benefit is that this path does not depend on the Python version like `/usr/local/lib/python3.*/.../motioneye`.

**Comment by MichaIng** [comment]
Marking as closed. We can discuss in dedicated issues/PRs whether/which files to move outside of `motioneyes` sub directory and whether/how to install some to `/usr/local/share/motioneye` when installed as system/root module.

**Pull request closed without merging**
