### PR TITLE
Change `onResponse` argument to avoid dependency on error pages

### LINKED ISSUE #2206: `An error occurred. Refreshing is recommended` when using custom 404 or 403 pages
I'm using `traefik` as a reverse proxy, and when using custom error pages, it overrides the 404 and 403 pages for any service it runs. This means when motioneye requests for `/login` or `/config/list` and expects 403 with a json but it gets a custom html error page. This causes the following error:

 

I understand if you think this is not a motioneye issue, since everything works fine when I don't use custom error pages. I just wondering if you can make a change to not fail for invalid 403 errors?

### PR DESCRIPTION
**Pull request by kdheepak**
Fixes #2206

### CODE REVIEW

**Comment by MichaIng** [comment]
Many thanks for your PR.

I played a bid around with this and indeed, the 403 JSON seems to be always exactly this. So it seems to be safe to apply so that the frontend does not require the `request.responseJSON` to be defined. But I'd like to someone else reviewing this before we merge. Any objections of you guys?

**Comment by kdheepak** [comment]
Sure, I can rebase in a few hours! Thanks for reviewing the PR!

**Comment by kdheepak** [comment]
I've rebased on the latest `dev`, but I haven't been able to test it yet. I might be able to test it tomorrow.

**Review by MichaIng — DISMISSED** [review]

**Comment by MichaIng** [comment]
Just to add this info right here:
- The aim of this PR is to enable support for proxies in front of motionEye which send custom 403 responses.
- This may be a custom HTML document, where `request.responseJSON` is not defined/valid, causing an error.
- motionEye itself seems to always create the `{prompt: true, error: "unauthorized"}` JSON, so sending this explicitly would not change anything without such a proxy, but avoids the error in case of such a proxy, overwriting it's response with the hardcoded JSON in the frontent/JavaScript.

**Comment by MichaIng** [comment]
I added a code comment about it and will merge when check go green.

**Comment by MichaIng** [comment]
Strange, the Docker build failed on installing `babel` or ARMv7 on your fork, but it succeeded here on the PR run. Would be unrelated anyway. I think we need to align the Python module installs on all distros anyway, i.e. not using the distro's Python module packages but `get-pip.py` instead. Will do a suggestion via PR now, but merging this PR first, which definitely does not cause the failure.

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
