### PR TITLE
Update external assets

### PR DESCRIPTION
**Pull request by MichaIng**
Additionally minified versions are consequently used.

@jmichault 
Where did you get `gettext.min.js` from?

### CODE REVIEW

**Comment by MarcelCoding** [comment]
maybe here https://github.com/guillaumepotier/gettext.js/tree/master/dist

**Review by MarcelCoding — DISMISSED** [review]

**Comment by MichaIng** [comment]
> maybe here https://github.com/guillaumepotier/gettext.js/tree/master/dist

Indeed it is, the old v0.5.3 matches. I'll test the latest version locally and in case add the update to this PR.

> in the future, we maybe should grab these from npm

Might be overkill to use Node.js/npm for those few static assets. A `package.json` would enable us to stay updated via dependabot, create workflows for rebuilding/minifying etc. But would be also possible to create a scheduled non-npm workflow which checks asset versions an in case creates PRs for updating them automatically.

**Comment by MarcelCoding** [comment]
Your is would probably be better.

**Comment by MichaIng** [comment]
I'm surprised that I couldn't find a single error/required change in our JavaScript. This shows somehow that jQuery is only used for the very basic query features, and of course by the other used jQuery modules. But we may easily be able to get rid of it all together, plain JavaScript in the meantime supports most of the features that made jQuery once popular, and now often obsolete 😉.

**Comment by MarcelCoding** [comment]
I would like typescript :)

**Review by MarcelCoding — APPROVED** [review]

**Comment by MichaIng** [comment]
> I would like typescript :)

Maybe one day when there is time and mood for a larger rework 😄.

**Comment by jmichault** [comment]
> Additionally minified versions are consequently used.
> 
> @jmichault Where did you get `gettext.min.js` from?

I took it from another project, for which I took it from... I can't remember, but it seems to be :   https://github.com/guillaumepotier/gettext.js/blob/4cb91894f6f59b2165eb7fe9c9f9fa958d6c9213/lib/gettext.js

**Comment by MichaIng** [comment]
This repo at least seems to be the official/original one. Translations work fine with the latest v1.1.1 🙂.

**Pull request merged**
