### PR TITLE
static/img/README.md

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/motioneye-project/motioneye/blob/static/img/README.md/motioneye/static/img/README.md

### CODE REVIEW

**Comment by MichaIng** [comment]
What is the aim of this? We shouldn't store anything in `static/` which is not really used by the motionEye frontend.

**Comment by cclauss** [comment]
Did you click on the URL in the commit message?

**Comment by cclauss** [comment]
Like most README files, this one is meant to describe the contents of the directory so show each visitor does not need to open up each file to understand its contents.

**Comment by MichaIng** [comment]
Hmm, I mean it's about image files, not sure whether it's important to describe/show them in a readme, when they can be simply opened.

The problem I have with it is that I generally do not like to have unused files in the Python package (while they can be excluded) and that it it requires us to update this readme whenever we add/remove/rename any of these files.

**Pull request closed without merging**
