### PR TITLE
Fix flake8 which moved from GitLab to GitHub

### PR DESCRIPTION
**Pull request by MichaIng**
See: https://omeralkin.com/flake8-takedown-gitlab-repo/

### CODE REVIEW

**Comment by cclauss** [comment]
You might want to do `pre-commit autoupdate` and then `pre-commit run --all-files`

**Comment by MichaIng** [comment]
A scheduled GitHub actions for this, with auto-PR if updates are available, would be great. But for now, this is to apply a fix only.

**Comment by MichaIng** [comment]
I just set up https://pre-commit.ci/, but it looks for the config in default branch. A GitHub workflow without external service and full control would be probably better anyway.

**Review by cclauss — APPROVED** [review]

**Comment by cclauss** [comment]
https://github.com/PyCQA/flake8/tags v5.0.4

**Pull request merged**
