### PR TITLE
Add 4k to the common resolutions list

### PR DESCRIPTION
**Pull request by lmilius**
I find myself having to use the custom option when setting up 4k cameras so having it as one of the resolutions in the list of dropdowns would be more convenient.

I didn't see a contributing section on the wiki, so let me know if there are other things that need to be updated to make this work. Thanks!

### CODE REVIEW

**Comment by lmilius** [comment]
Changed the mysql lib package to the mysql-common for amd64, similar install error was found here with the solution: https://www.raspberrypi.org/forums/viewtopic.php?t=191380#p1214084

**Comment by MichaIng** [comment]
Many thanks for your pull request. Makes sense to add 4k to the native menu nowadays 👍. Could you rebase or recreate the PR onto current `dev` branch please? The `utils.py` has been split, so the file to edit now is: https://github.com/motioneye-project/motioneye/blob/dev/motioneye/utils/__init__.py

The Dockerfile change has become obsolete, `default-libmysqlclient-dev` is used in the meantime.

**Comment by MichaIng** [comment]
When rebasing, there is no change left, which triggers the PR being closed automatically. I redid the changed on current `dev` branch: #2366
@lmilius let me know if you want to be author of the commit in the commit history, I think then you'd need to create the PR or share a signoff name + mail with me that I can append to the commit text.

**Comment by lmilius** [comment]
No problem, just glad to see it be integrated, thanks!

**Comment by MichaIng** [comment]
Okay great. Definitely reasonable, modern cameras, including Raspberry Pi camera modules, support 4k 👍.

**Pull request closed without merging**
