### PR TITLE
Python3 experimental support

### PR DESCRIPTION
**Pull request by Vlsarro**
This is an attempt to migrate motionEye to python 3.

Firstly I just ran 2to3 program and manually fixed any leftovers. Also did general refactoring (PEP8). Secondly I have splitted handlers into separate modules because it was hard to work with all these classes in one file so I just decided to decouple them a little bit. I have also tried to split utils functions into different modules because there were many disparate functions, some of which could be combined into one group (according to their purpose). Ctl files also were moved to their own distinct package.

Next I have added some basic tests. Only a few unfortunately. I sincerely wanted to test all functionality related to IOStream usage, but couldn't wrap my head around how to do that, always got some errors which set me back. Alas, may be in the future.

In addition I have tried to make use of async/await syntax to simplify motionEye code.

Overall the python3 branch looks quite good to me and satisfies my needs, but I'd really appreciate if someone with good knowledge of motionEye inner workings tested the project functionality. Because there is a clear lack of unit and integration tests and I didn't checked all the stuff.

### CODE REVIEW

**Comment by ccrisan** [comment]
@Vlsarro this is great work! However having everything in a single PR like this is going to be very difficult to review.

**Comment by herostrat** [comment]
Hallo @ccrisan,

this branch is really promising. With the few additional PRs all trying to bring python3 to motioneye a lot of work is being wasted.
Python2 is dead.

What can I do to help you gtm? I understand that this are a lot of changes and not all of them are python3 specific.

Best

**Comment by ccrisan** [comment]
@herostrat this PR has a lot of stuff that has been automatically converted/adjusted (or at least that's my impression). There are changes that simply break the functionality of motionEye.

I haven't had the time to take a serious look over it, since it's quite a huge amount of changes, but trying to run it will simply show various functionalities that don't work.

I'm not saying this PR doesn't contain good stuff. What I'm saying is that it probably has good changes that would be welcomed (either for py2 or for py3), but given the way they are put together, noone's going to be able to read through them and actually apply/merge them.

**Comment by kleini** [comment]
I think, we should merge smaller merge requests into the python3 branch and try to get that working. Once the python3 branch works, we should merge that back to dev. So, this can become a working scheme, where people can start to participate.

**Comment by herostrat** [comment]
@ccrisan First, thanks a lot for the answer. I unterstand and feel you, I wouldn‘t want to review it myself 👍 

Anyone interested in a working group to reduce dublication of efforts and makes motioneye ready for python3?

**Comment by rivimey** [comment]
Bump! :-)

**Comment by rivimey** [comment]
I've cloned Visarro's repo and had a play, using my existing 0.42 setup.
It doesn't work straight away.

I needed to install tornado, pycurl, jinja2 ... would it be beneficial to have a requirements.txt file?

In motioneye/utils.py:
Function compute_signature for startswith throws an error because 'body' is a byte array not a string, so '---' should be b'---'

There is an issue with for y in range(ny): in parse_editable, same file. In that function, for me, the range(ny) errors out because 'ny' is a float. I put some debugging just before it:

    +    logging.error('parse mask image: w %(width)s h %(height)s mw %(MASK_WIDTH)s nx %(nx)s ny %(ny)s'
    +       % {
    +               'MASK_WIDTH': MASK_WIDTH,
    +               'width': str(width),
    +               'height': str(height),
    +               'nx': str(nx),
    +               'ny': str(ny)
    +       })

and it printed:

    ERROR: parse mask image: w 2560 h 1536 mw 32 nx 32 ny 18.2
 
I am not sure what is intended here, so will move on by casting ny to int, but I'm sure that's not the right answer.  .... and indeed, when I do that I get 'list index out of range at line 1009 ( `pixel = pixels[py * width + px]` )

I keep getting an error 'finish() called twice' from the tornado code via:
  File "/home/ruth/motioneye/motioneye/motioneye/handlers/base.py", line 84, in finish -- RequestHandler.finish(self, chunk=chunk)

With that, I get most of the web page working, including login, auth, settings page. No video showing though I do see a camera icon, and those are highlighted.

I'll stop here for the moment. Hope the above is useful.

**Comment by Vlsarro** [comment]
I have a new version of this branch with fixed bugs, may be later I'll add new commits

**Comment by mgrouch** [comment]
@Vlsarro

Vlsarro I'd rather use your fork at this point as it supports python3.
How can I build it after I do git clone?
 Thanks

**Pull request merged**
