### PR TITLE
motioneye_init: stop and disable conflicting motion.service

### PR DESCRIPTION
**Pull request by MichaIng**
The motion package installs a motion systemd service, which can block camera devices and hence conflict with the motionEye-controlled motion processes.

We hence need to assure that this service is stopped and disabled, before we can start and enable out motioneye.service.

See https://github.com/motioneye-project/motioneye/issues/2810#issuecomment-2102835451, #2816 and other cases.

### CODE REVIEW

**Comment by MichaIng** [comment]
If someone is able to identify the issue with the `test_python` test, that would be great. See the commit message where I ignore their outcome. The logs are of course still there, even when the result is green. I guess the true error is to be found in the mypy test before the pytest failure, about incompatible variable types in the test classes. In any case, it is an issue with the test itself, not with the code it tests.

**Comment by zagrim** [comment]
I wonder if the test failure is related to this: https://github.com/tornadoweb/tornado/pull/3374

**Review by zagrim — APPROVED** [review]
The actual change (disabling the conflicting service) looks ok to me :+1:

**Comment by MichaIng** [comment]
Great find, yes that will be it. I subscribed to the PR and will un-ignore the tests, once it was merged and released.

**Pull request merged**
