### PR TITLE
Add async to improve page load times.

### PR DESCRIPTION
**Pull request by ZeroDot1**

### CODE REVIEW

**Comment by ZeroDot1** [comment]
I can confirm that it now loads much better under real conditions.

**Comment by MarcelCoding** [comment]
May also add `defer`

**Comment by MichaIng** [comment]
I'd generally also use `defer` to assure that the whole DOM is rendered before any JavaScript is executed. Could you please rebase and resolve conflicts? In the meantime `async` and `charset="utf-8"` has been added in some cases. In case you agree, you may replace it with `defer` in all cases.

**Comment by MichaIng** [comment]
Sometimes I hate GitHub (desktop and web) for making it sometimes impossible to achieve what you want, like here a clean rebase onto current `dev`. It was impossible to push local changes without first pulling an empty merge commit, which means all changes which happened on `dev` since this PR was opened are shown as changes here, even they aren't 😞. And of course it is not possible to squash these. I'll try with `git` CLI on Linux.

**Comment by MarcelCoding** [comment]
You can easily squash commit:
1. `git reset --mixed <id>` - resets to the specified commit but don't touch any files
2. `git add .` - add all files to git
3. `git commit ...` - now all committed after the in the first task are squashed

**Comment by MichaIng** [comment]
Just not from GitHub desktop or web interface. Doing it just now with CLI on Linux. But I may not have permissions to push to this branch, when not given through GitHub as part of the PR (allowing maintainer edits).

**Comment by MichaIng** [comment]
Okay, luckily it worked 🙂.

**Comment by MichaIng** [comment]
Okay the AJAX login call is done on `dev` as well, hence not related to this PR.

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
