### PR TITLE
WIP: Motioneye Python3 Work

### PR DESCRIPTION
**Pull request by herostrat**

### CODE REVIEW

**Comment by ccrisan** [comment]
@herostrat I don't think there's any point in using `list(...)` when iterating over dictionary items (i.e. when used in one of the `for`-loop constructions).

**Comment by herostrat** [comment]
I agree, I changed it after the suggestion of 2to3 and wanted to check if (and why) there it showed the suggestion.

In this case I could not find a difference in behavior, so at least it does not regress, although I don't understand why it should be changed in the first place.

I will revert those changes before I submit it for review.

**Comment by MichaIng** [comment]
Just to avoid doubled work, there is another PR open about this already: #1805

Looking forward for this, as of Python 2 deprecation, making it increasingly difficult / unreasonable to keep supporting Python 2 dependant software.

**Comment by mweinelt** [comment]
> Just to avoid doubled work, there is another PR open about this already: #1805

The problem with the other pull request is, that it is too big too review, test and merge properly. So I think it would be better to get small changes into the python3 branch again and again, so the volume of changes remains reviewable.

**Comment by MichaIng** [comment]
I rebased the PR and resolved conflicts, and this is now mostly obsolete, as solved in current dev already 🙂. I'll merge it however to have the trailing spaces removed 😉.

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
