### PR TITLE
GitHub Action to lint Python 3 branch

### PR DESCRIPTION
**Pull request by cclauss**
Like #2308 but on the `python3` branch.

Test results: https://github.com/cclauss/motioneye/actions

### CODE REVIEW

**Comment by cclauss** [comment]
@MichaIng Your review, please.

**Comment by cclauss** [comment]
Please revert that change.  It was done against an earlier commit.  We are in a Python 3 environment so pip is Python 3's pip.

**Comment by cclauss** [comment]
We are in a Python 3 environment so pip is Python 3's pip.

**Comment by cclauss** [comment]
No longer needed.

**Comment by MichaIng** [comment]
> We are in a Python 3 environment so pip is Python 3's pip.

I usually prefer to be explicit. E.g. when one installs the distributions `python` package, `pip` calls Python 2. But fine with me as long as it works in the particular workflow.

**Comment by MichaIng** [comment]
I think some of your changes are still missing in `python3`, can you check: https://github.com/motioneye-project/motioneye/pull/2312/commits/e0939e9

**Pull request closed without merging**
