### PR TITLE
Docker - Fix uid/gid replacement as motion user does not exist at that time.

### PR DESCRIPTION
**Pull request by ultratoto14**

### CODE REVIEW

**Comment by MichaIng** [comment]
Makes sense, the `motion` user does not exist before `motioneye_init` which installs the `motion` package. But actually I do not understand the logic behind thus UID/GID change in general:
- We place both with `0`, but is `0` not use by the root user, so that we have a conflict afterwards?
- Why don't we just leave them as they are, there is not a single code which uses a specific UID/GID, but the `motion` user is invoked by its name always.

**Comment by ultratoto14** [comment]
I'm using a NAS to run the docker image of motioneye. Docker is running as root on that nas.
On the previous version, the motion user was updated using the same `sed` commands I moved in this PR. So the previously  created files where using 0/0 as uid/guid. So without using these commands, the new image will not be compatible with an old version anymore.
You can have multiple users with the same uid, it's not really a problem (even if it's not recommended). In the other case, it implies that users need to change the owners and rights of shared files with container and this need to be documented.
I may try one day to check if we can use the original `motion` user and how to share volumes with the container but unfortunately, it will not be soon, as I do not have any time available.

**Review by MarcelCoding — APPROVED** [review]

**Comment by MichaIng** [comment]
> I may try one day to check if we can use the original `motion` user and how to share volumes with the container but unfortunately, it will not be soon, as I do not have any time available.

Double use of the same UID/GID really sounds like reason for various issues which are hard to debug when not having that fact in mind. Also, if I'm not mistaken, it basically means that `motion` user/group get `root` owner/group permissions within the container, since those are obtained form the UID/GID, not the name. With this, there is not any point left of running motionEye as `motion` user then, but we could simply run it as root directly.

If it is about volume write permission, what about simply `chown -R motion:motion` via `entrypoint.sh`? I'm not sure whether there is a translation between container and host UID/GID: If this causes the files on the host to have either invalid UID/GID or to be owned by an unintended user/group with the same IDs than motion/motion inside the container, then this is not good idea. Then it's better to just run motionEye explicitly root inside the container instead of giving it root user and group ID. It may even cause unexpected issues when motion has UID 0 but is not really root, like motionEye thinks is has root permissions, hence shows shutdown/reboot buttons in the web interface (it checks the ID, not the name), but those may then not work if, other than file permissions, it depends on the actual user and not on the UID.

**Comment by MichaIng** [comment]
The current `ccrisan/motioneye` container runs motionEye as root, right? So we can or need to assume that existing volumes are root-owned as well.

I checked back as well on how Docker handles UID/GID between container and host, and it does nothing, which surprises me quite a lot for the most widely used container engine. This is terrible for host/container volume volume management since you must either run the container + process as root or you must manually create a dedicated user+group on the host and reuse the same IDs in the container. I'd have expected to have an automated translation, e.g. everything on a volume being root:root owned on the host, regardless how it is in the container, with the option to define a different host UID/GID and again optional individual UID/GID mapping:
- https://github.com/moby/moby/issues/22258
- https://github.com/moby/moby/issues/2259

Three options:
1. Pre-create motion user and group with explicit high/rare UID/GID and `chown` within the entrypoint. This way full security is assured within the motionEye process, but the container itself still runs as root and admins may find their volume files inaccessible after upgrading the container, since previously they could have chowned it host-side to any other user while the container was able to read/write everything as root.
2. Same as 2, but without the `chown` in entrypoint. That way we enhance security since the container itself can now run as `motion` user, no `su` required in the entrypoint etc. But admin must `chown` or `chmod` the volume files when upgrading the container to re-grant the newly used `motion` user R/W access. Not sure whether there is a way to inform users properly, e.g. at least printing a meaningful error message on missing R/W permissions or a message on container upgrade?
3. Run motionEye as root: That way we have no half faked security with the `motion` user but a transparent and failsafe insecure root execution. This basically maintains the behaviour of the current Docker container release. In case of motionEye, this assures that shutdown/reboot/SMB mount and other root-only features can be used.

**Comment by kleini** [comment]
Rootless containers is not about the used UIDs inside the container. It is about the permissions outside the container. On the host the container is then running only with user privileges not with root privileges. This is about vulnerabilities that allow to exit the container. You don't have then root privileges on the host.

**Comment by MichaIng** [comment]
Probably I mixed it up since you linked the namespace docs after the info for rootless support. So I guess you mean running the Docker daemon itself as non-root user, which requires certain OS packages and setup, so not something we can control or count on. But generally nice to know 🙂: https://docs.docker.com/engine/security/rootless/

**Comment by kleini** [comment]
When it comes to rootless containers, I would get rid of Docker first und use podman, containerd or CRI-O instead. There are container runtimes out there, that are far better than Docker.

**Comment by kleini** [comment]
All these container engines use OCI standardized container format and runtime interface. So there is no need to build other container images. I already run motioneye with podman. Running the Docker daemon is a security risk, as it has a network or Unix socket interface and runs as root.

Best would be to introduce UID 1000. This is standard for services running in containers without root privileges. Through an ENV variable this can be overwritten from outside on container start, if somebody needs something else.

**Comment by MichaIng** [comment]
> All these container engines use OCI standardized container format and runtime interface.

Ah right, for podman at least I should have known 😅.

> This is standard for services running in containers without root privileges.

Is that so? It is the default UID for the first created login user (since useradd/adduser start with UID 1000 for non-system users). E.g. on Raspberry Pi OS this is `pi`, on DietPi it's `dietpi`, Radxa ships their images with the `rock` user etc. At least with these SBC distro images, coming with a default login user, it has usually elevated privileged, being member of several system groups for video, audio, GPIO etc access OOTB, so from security point of view this isn't optimal. Additionally it means that this default login users may get additional privileges since `motion` adds it to at least `video` group for camera access. On the other hand, since that user is nearly assured to exist and being used, it may be very practical for admins to have files read/writable with their default login user. But from security POV I wouldn't mix those but instead aim to use a UID which has a very low change to exist on the host.

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Merging this now. It restores the currently intended behaviour and hence a functional Docker container. Tracking the discussed options to further enhance container security here: #2407

**Pull request merged**
